### ISSUE TITLE
Add installed_capacity_nameplate_kwp

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_datamodel#81]
add installed_capacity_nameplate_kwp to pv systems. 
Add this as optional, and if None, then use installed_capacity. 

This will be used as the name plate capacity given by the providers. 
The other will be used for ML training and ML preidctions

**Comment by peterdudfield** [comment]
LInked from https://github.com/openclimatefix/nowcasting_dataset/issues/692

**Comment by peterdudfield** [comment]
might need this - https://stackoverflow.com/questions/36579355/sqlalchemy-set-default-value-of-one-column-to-that-of-another-column, to help set a default

**Comment by JackKelly** [comment]
should we consider renaming `installed_capacity`, to help distinguish it from `installed_capacity_nameplate_kwp`? Otherwise the two could easily be interpreted as synonyms?

e.g. `installed_capacity_inferred_kwp` (if we're inferring it from the timeseries)?

And to include the physical unit of measurement in `inferred_capacity`?
